config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  resources :users do
    resources :posts
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :photo,
                    styles: {
                              thumb: '100x100>',
                              square: '200x200#',
                              medium: '300x300>'
                            },
                    bucket: :YOUR_BUCKET_NAME

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    registration_params = [:email, :name, :phone, :password, :password_confirmation, :photo]
    devise_parameter_sanitizer.for(:sign_up) {
        |u| u.permit(registration_params)
      }
    devise_parameter_sanitizer.for(:account_update) {
        |u| u.permit(registration_params << :current_password)
      }

  end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @user = current_user
    @user.posts.create(safe_post_params)
    redirect_to user_posts_path(@user)
  end

  private

  def safe_post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @user_count = User.all.count
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_nav.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="/"><%= image_tag 'logos/logo.png', :class => "navbar-brand logo" %></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <li><%= link_to "New Post", new_user_post_path(current_user) %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
          
            
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

app/views/layouts/application.html.erb
  <%= render "layouts/nav" %>

  <div class="container">
    <div class="row">
      <div class="col-md-8">
        
          <%= yield %>

      </div>

      <div class="col-md-4">
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        <h2>About Blogr</h2>

        <p>Normally, both your asses would be dead as fucking fried chicken, but you happen to pull this shit while I'm in a transitional period so I don't wanna kill you, I wanna help you. But I can't give you this case, it don't belong to me. Besides, I've already been through too much shit this morning over this case to hand it over to your dumb ass. </p>

        <p>Well, the way they make shows is, they make one show. That show's called a pilot. Then they show that show to the people who make shows, and on the strength of that one show they decide if they're going to make more shows. Some pilots get picked and become television programs. Some don't, become nothing. She starred in one of the ones that became nothing. </p>


      </div>

    </div><!-- .row -->
  </div> <!-- .container -->
</body>
</html>

app/views/posts/index.html.erb
<%= image_tag @user.photo.url(:medium) %>
<h2><%= @user.name %>'s posts!</h2>

<ul>
<% @posts.each do |post| %>
  <li><%= link_to post.title, user_post_path(@user, post) %></li>
<% end %>
</ul>

app/views/posts/new.html.erb
<h1>New post by you, <%= current_user.name %></h1>

<div>
  <%= form_for [current_user, @post] do |f| %>
    <p>Title: <%= f.text_field :title %></p>
    <p>Body: <%= f.text_area :body %></p>
    <p><%= f.submit "Post!", class: "btn btn-primary btn-md" %></p>
  <% end %>
</div>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<h3>by <%= link_to @post.user.name, user_posts_path(@post.user) %></h3>

<p><%= @post.body %></p>

app/views/welcome/index.html.erb
<h1>Welcome to Blogr!</h1>

<h3>We have <%= @user_count %> users! be our next user!</h3>

<ul>
  <% @users.each do |user| %>
  <li><%= link_to user.name, user_posts_path(user) %></li>
  <% end %>
</ul>